//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISEventManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryCategory
    {
        public GalleryCategory()
        {
            this.Galleries = new HashSet<Gallery>();
        }
    
        public byte GalleryCategoryID { get; set; }
        public string CategoryName { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public bool IsAdvertise { get; set; }
    
        public virtual ICollection<Gallery> Galleries { get; set; }
    }
}
