//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISEventManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointsForTask
    {
        public byte PointsForTaskID { get; set; }
        public string TaskName { get; set; }
        public short PointsGain { get; set; }
    }
}
