//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISEventManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public System.Guid ReviewID { get; set; }
        public long EventID { get; set; }
        public long UserID { get; set; }
        public byte Rating { get; set; }
        public string ReviewComment { get; set; }
        public string SuggestionsToMakeItBetter { get; set; }
        public bool PostAsAnonymous { get; set; }
        public string WhatLikedAboutEvent { get; set; }
        public long LikedCount { get; set; }
        public long DisLikedCount { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
