//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISEventManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagRel
    {
        public System.Guid TagRelID { get; set; }
        public System.Guid TagID { get; set; }
        public long EventID { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
