//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISEventManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Events = new HashSet<Event>();
            this.Hosts = new HashSet<Host>();
            this.Inviteds = new HashSet<Invited>();
            this.Reviews = new HashSet<Review>();
            this.UserPoints = new HashSet<UserPoint>();
            this.UserResponseToEvents = new HashSet<UserResponseToEvent>();
        }
    
        public long UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public long CurrentPoint { get; set; }
        public bool IsAuthurized { get; set; }
        public bool IsFlagged { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Host> Hosts { get; set; }
        public virtual ICollection<Invited> Inviteds { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<UserPoint> UserPoints { get; set; }
        public virtual ICollection<UserResponseToEvent> UserResponseToEvents { get; set; }
    }
}
