//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISEventManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPoint
    {
        public System.Guid UserPointID { get; set; }
        public long UserID { get; set; }
        public byte PointGained { get; set; }
    
        public virtual User User { get; set; }
    }
}
