//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISEventManagement.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venu
    {
        public Venu()
        {
            this.Events = new HashSet<Event>();
        }
    
        public long VenuID { get; set; }
        public string VenuName { get; set; }
        public string VenuAddress { get; set; }
        public byte CountryId { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
