//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISEventManagement.Models.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventManagementEntities : DbContext
    {
        public EventManagementEntities()
            : base("name=EventManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventType> EventTypes { get; set; }
        public DbSet<Gallery> Galleries { get; set; }
        public DbSet<GalleryCategory> GalleryCategories { get; set; }
        public DbSet<Host> Hosts { get; set; }
        public DbSet<Invited> Inviteds { get; set; }
        public DbSet<PointsForTask> PointsForTasks { get; set; }
        public DbSet<Review> Reviews { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<TagRel> TagRels { get; set; }
        public DbSet<TempUpload> TempUploads { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserPoint> UserPoints { get; set; }
        public DbSet<UserResponseToEvent> UserResponseToEvents { get; set; }
        public DbSet<Venu> Venus { get; set; }
    }
}
